mode: deployment

image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s

extraEnvs:
  - name: K8S_CLUSTER_NAME
    value: "docker-desktop"

replicaCount: 1

presets:
  clusterMetrics:
    enabled: true
  kubernetesEvents:
    enabled: true

config:
  receivers:
    k8s_cluster:
      collection_interval: 30s
      metrics:
        k8s.replicaset.desired:
          enabled: false
        k8s.replicaset.available:
          enabled: false 
    jaeger: null
    zipkin: null
  processors:
    transform/events:
      error_mode: ignore
      log_statements:
        - context: log
          statements:
            - set(attributes["watch-type"], body["type"]) where IsMap(body) and body["type"] != nil
            - merge_maps(attributes, body, "upsert") where IsMap(body) and body["object"] == nil
            - merge_maps(attributes, body["object"], "upsert") where IsMap(body) and body["object"] != nil
            - merge_maps(attributes, attributes["metadata"], "upsert") where IsMap(attributes["metadata"])
            - set(attributes["k8s.pod.name"], attributes["regarding"]["name"]) where attributes["regarding"]["kind"] == "Pod"
            - set(attributes["k8s.node.name"], attributes["regarding"]["name"]) where attributes["regarding"]["kind"] == "Node"
            - set(attributes["k8s.job.name"], attributes["regarding"]["name"]) where attributes["regarding"]["kind"] == "Job"
            - set(attributes["k8s.cronjob.name"], attributes["regarding"]["name"]) where attributes["regarding"]["kind"] == "CronJob"
            - set(attributes["k8s.namespace.name"], attributes["regarding"]["namespace"]) where attributes["regarding"]["namespace"] != nil
            - set(severity_text, "UNKNOWN") where severity_text == nil
            - set(severity_number, 0) where severity_number == nil
    batch/events:
      timeout: 10s
      send_batch_size: 100
    batch: {}

  exporters:
    otlp:
      endpoint: "http://bindplane-gateway-alb.your-domain.com:4317"
      tls:
        insecure: true
      headers:
        "x-honeycomb-dataset": "traces"
    otlp/k8s-metrics:
      endpoint: "http://bindplane-gateway-alb.your-domain.com:4317"
      tls:
        insecure: true
      headers:
        "x-honeycomb-dataset": "k8s-metrics"
    otlp/k8s-events:
      endpoint: "http://bindplane-gateway-alb.your-domain.com:4317"
      tls:
        insecure: true
      headers:
        "x-honeycomb-dataset": "k8s-events"

  service:
service:
  pipelines:
    traces: null
    metrics:
      exporters: [otlp/k8s-metrics]
    logs:
      processors: [memory_limiter, transform/events, batch]
      exporters: [otlp/k8s-events]

